
name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build-develop:
    runs-on: ubuntu-22.04
    environment: develop
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: coin98-be

    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch

    - name: Testing
      shell: bash
      run: |
        pwd
        ls -la
        echo "${{ steps.extract_branch.outputs.branch }}"
        echo "${{ secrets.HOST }}"
        echo "${{ env.HOST }}"

  build-production:
    runs-on: ubuntu-22.04
    environment: production
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: coin98-be

    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch

    - name: Testing
      shell: bash
      run: |
        pwd
        ls -la
        echo "${{ steps.extract_branch.outputs.branch }}"
        echo "${{ secrets.HOST }}"
        echo "${{ env.HOST }}"